### ISSUE TITLE
Some comments about the first cryptex version

### ISSUE THREAD

**Issue by frispete** [tuxxy/pycryptex#1]
Hi Tuxxy,

your current design is focused on one shot {de,en}cryption, which is fine, but doesn't apply to bigger payloads well. This is underlined by base64 {de,en}coding the result.

In that light, don't know, if 256 bit mode of AES buys you **much** other than *raising* the ciphertext size.
See https://www.schneier.com/blog/archives/2009/07/another_new_aes.html, and Bruce related [comment](https://www.schneier.com/blog/archives/2009/07/another_new_aes.html#c386957).
Please note, that the described attack is very artificial as [such](http://crypto.stackexchange.com/questions/1549/related-key-attacks-on-aes) and should not trouble you.

I asked Helder to consider making the number of rounds an option, but he declined [that](https://github.com/Legrandin/pycryptodome/issues/59).

**Comment by tuxxy** [comment]
Hi frispete,

Thank you for your comments. AES operates on a fixed block size of 128 bits making the ciphertext size unaffected by the keysize by any means.

As for encoding/decoding the data with Base64, this is meant as an example for a high level Fernet-like implementation of AES in GCM. I would go out on a limb to say that most people don't have a need to encrypt exceptionally large files that wouldn't ordinarily fit in memory. Cryptography.io also has this issue with their Fernet implementation. Now, I would love to add a solution to this, but I'm appealing to most people first who don't need this solution.

As for the attack you mentioned, it's highly complex and not practical by any means. Schneier himself says:
> The attacks presented in the papers are not practical -- they're far too complex...

As it is a key-related attack, it requires some very specific pretexts for it to even be possible.

Modifying the number of rounds in AES is not a practical change. As Legrandin said, it wouldn't be AES anymore and would be very detrimental to interoperability. This might be cause for alarm for cryptanalysts, as well.

Thanks
